spring:
  application:
    name: api-ithappens
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/ithappens
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
    #url: jdbc:h2:file:~/h2db
    #username: admin
    #password: admin
    #driver-class-name: org.h2.Driver
    #initialization-mode: always
    
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      path: /h2
      enabled: true
      

server:
  port: 8080